language: node_js
node_js:
  - v5
  - v4
  - '0.12'
  - '0.10'

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
      - libleptonica-dev
      - libtesseract-dev