language: node_js
node_js:
  - v5
  - v4
  - '0.12'
  - '0.10'
before_install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         wget --no-check-certificate https://www.cmake.org/files/v3.5/cmake-3.5.0-Linux-i386.tar.gz
      && tar -xzf cmake-3.5.0-Linux-i386.tar.gz
      && sudo cp -fR cmake-3.5.0-Linux-i386/* /usr
      && sudo apt-get -qq update
      && sudo apt-get -qq install g++-4.8 libleptonica-dev libtesseract-dev
      && export CXX="g++-4.8"
      && export CC="gcc-4.8"
      ;
    else
         brew update
      && brew unlink cmake
      && brew install cmake tesseract
      ;
    fi